"""remove temporary table for migration test

Revision ID: 7c539cefd827
Revises: aecd1aa869db
Create Date: 2023-11-30 20:43:39.725998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c539cefd827'
down_revision = 'aecd1aa869db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_migration_test_table', schema=None) as batch_op:
        batch_op.drop_index('ix_temporary_migration_test_table_id')

    op.drop_table('temporary_migration_test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_migration_test_table',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('temporary_migration_test_table', schema=None) as batch_op:
        batch_op.create_index('ix_temporary_migration_test_table_id', ['id'], unique=False)

    # ### end Alembic commands ###
