name: test_flask_api

on: [push]

jobs:
  run_api:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: set up python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        echo installing python dependencies
        python3 -m pip install -r requirements.txt
        echo setting up new venv auth
        python3 -m venv auth
        source env.sh
    - name: lint with flake8
      run: |
        echo installing flake8 linter
        python3 -m pip install flake8
        echo linting with forced fail pipeline for errors
        flake8 . --count --exclude auth --select=E9,F63,F7,F82 --show-source --statistics
        echo linting warnings
        flake8 . --count --exclude auth --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: test with pytest
#      run: |
#        echo installing pytest
#        python3 -m pip install pytest
#        echo pytest
#        pytest
    - name: test running app
      run: |
        timeout 20 flask run || echo pass
