name: test_flask_api

on: [push]

jobs:
  run_api:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: set up python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        python3 -m pip install -r requirements.txt
        python3 -m venv auth
        source env.sh
    - name: lint with flake8
      run: |
        python3 -m pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: test with pytest
      run: |
        python3 -m pip install pytest
        pytest
    - name: test running app
      run: |
        timeout 20 flask run || echo pass
